# Generated by Django 5.2 on 2025-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='box_creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100, unique=True)),
                ('number_phone', models.IntegerField()),
                ('town', models.CharField(max_length=100)),
                ('name_organization', models.CharField(max_length=100)),
                ('rang', models.CharField(max_length=100)),
                ('psw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='box_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100, unique=True)),
                ('psw', models.CharField(max_length=50)),
            ],
        ),
    ]
