# Generated by Django 5.2 on 2025-04-26 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackatonweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='name_organization',
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='hackatonweb.boxmember'),
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teams', models.ManyToManyField(related_name='fights_as_team', to='hackatonweb.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fights_as_winner', to='hackatonweb.team')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='fights',
            field=models.ManyToManyField(to='hackatonweb.fight'),
        ),
    ]
